-- ============================================================================
-- state_sections.sql  —  the 50-state statutory corpus, ONE TABLE PER STATE.
--
-- WHY PARTITIONED (one logical table, a physical sub-table per state):
--   State law is a different beast from the federal corpus: ~40 source sites,
--   wildly different HTML, and huge volume (California alone is ~162k sections).
--   We keep it OUT of document_sections so its quirks never pollute federal
--   browse/search. And within it, we LIST-partition by state_code so every
--   state lives in its own physical table (state_sections_ca, _tx, …):
--
--     • a browse/search scoped to ONE state only touches that state's partition
--       (partition pruning) — we never scan all 50 unless a user asks for "all";
--     • "search every state" is still ONE query against the parent — no 50-way
--       UNION, no 50 PostgREST endpoints (the frontend sees one table);
--     • rebuilding a state is `TRUNCATE state_sections_ca` — instant, isolated,
--       and can't touch any other state;
--     • a bad parse for one state can't bloat another state's indexes.
--
-- THE DATA MODEL (deliberately dumb — "think of it as folders"):
--   Every row is ONE leaf of statute text plus the names of the folders it lives
--   in. `path` is the folder hierarchy outer->inner, e.g.
--       {'California Codes','Labor Code','Division 5','Part 1','Chapter 6'}
--   `heading` is the leaf's own title ("§ 7856 ..."), `body_text` is the hunk of
--   law. That's all the front end needs to render it nested. Everything the
--   scrape captured beyond that (nav, history notes, annotations) is trash and
--   never lands here.
--
-- THE LOADER DOESN'T CHANGE: state_ingest.py still does
--   `INSERT INTO public.state_sections ...` — Postgres routes each row to its
--   state's partition automatically by state_code.
--
-- HOW TO RUN (on the headless box, as superuser `k`):
--     psql -d self_law -f scripts/state_sections.sql
--
-- Idempotent for the partitions/indexes/grants. NOTE: this DROPs and recreates
-- the parent (the only prior data was an AZ sample) to convert a previously
-- non-partitioned table — re-run the ingest to repopulate from the scrape.
-- ============================================================================

\set ON_ERROR_STOP on

CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- Convert from the old non-partitioned table. Safe: the only rows ever loaded
-- were an AZ --limit sample, fully regenerable from /mnt/sdb1/States.
DROP TABLE IF EXISTS public.state_sections CASCADE;

-- ── Parent (partitioned by state) ───────────────────────────────────────────
-- Constraints on a partitioned table must include the partition key, so the PK
-- and the upsert UNIQUE both carry state_code (UNIQUE already did).
CREATE TABLE public.state_sections (
  id          bigint GENERATED BY DEFAULT AS IDENTITY,

  state       text   NOT NULL,            -- 'California'
  state_code  text   NOT NULL,            -- 'CA'  (USPS, our short key + partition key)

  path        text[] NOT NULL,            -- folder hierarchy, outer -> inner
  heading     text,                       -- the leaf's own title
  section_num text,                       -- '7856', '10-120', '1.01' (for sort/lookup)

  body_text   text   NOT NULL,            -- the law, paragraphs joined by blank lines
  body_md     text,                       -- same, light markdown (lists/subsections)
  word_count  integer,

  source_url  text   NOT NULL,            -- provenance: the exact page we parsed
  sort_key    text,                       -- natural-sort key for stable browse order

  -- body_text is bounded before to_tsvector: a single tsvector cannot exceed
  -- 1 MB (Postgres hard limit), and a few statute sections (e.g. some IL acts)
  -- run past it. The full body_text is still stored intact; only the search
  -- vector is capped — the first ~500k chars are plenty for relevance.
  search_tsv  tsvector GENERATED ALWAYS AS (
                setweight(to_tsvector('english', coalesce(heading, '')), 'A') ||
                setweight(to_tsvector('english', left(coalesce(body_text, ''), 500000)), 'B')
              ) STORED,

  fetched_at  timestamptz NOT NULL DEFAULT now(),

  PRIMARY KEY (state_code, id),
  -- one row per source page per state; re-ingest upserts on this.
  UNIQUE (state_code, source_url)
) PARTITION BY LIST (state_code);

-- ── Indexes on the parent (propagate to every partition, present & future) ───
-- Full-text search backbone (mirrors document_sections_search_idx).
CREATE INDEX IF NOT EXISTS state_sections_search_idx
  ON public.state_sections USING gin (search_tsv);

-- Browse: walk the folder tree by prefix, ordered naturally within a state.
CREATE INDEX IF NOT EXISTS state_sections_browse_idx
  ON public.state_sections (state_code, sort_key);

-- Folder containment queries (path @> '{Labor Code}' etc.).
CREATE INDEX IF NOT EXISTS state_sections_path_idx
  ON public.state_sections USING gin (path);

-- Fuzzy fallback over heading + section number (typo tolerance).
CREATE INDEX IF NOT EXISTS state_sections_trgm_idx
  ON public.state_sections
  USING gin ((coalesce(heading, '') || ' ' || coalesce(section_num, '')) gin_trgm_ops);

-- ── One partition per state (all 50 + DC up front, so ingest never has to DDL) ─
DO $$
DECLARE
  c text;
  codes text[] := ARRAY[
    'AL','AK','AZ','AR','CA','CO','CT','DE','FL','GA','HI','ID','IL','IN','IA',
    'KS','KY','LA','ME','MD','MA','MI','MN','MS','MO','MT','NE','NV','NH','NJ',
    'NM','NY','NC','ND','OH','OK','OR','PA','RI','SC','SD','TN','TX','UT','VT',
    'VA','WA','WV','WI','WY','DC'
  ];
BEGIN
  FOREACH c IN ARRAY codes LOOP
    EXECUTE format(
      'CREATE TABLE IF NOT EXISTS public.state_sections_%s '
      || 'PARTITION OF public.state_sections FOR VALUES IN (%L)',
      lower(c), c);
  END LOOP;
END $$;

-- ── Grants (mirror document_sections: web role reads, service roles write) ───
-- Privileges on the parent cover routed INSERT/SELECT through the parent, which
-- is all the loader and PostgREST ever use.
GRANT SELECT ON public.state_sections TO selflaw_web;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.state_sections TO app_user, service_role, claude_mcp;

-- Tell PostgREST to pick up the new table.
NOTIFY pgrst, 'reload schema';
