/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhitepaperRouteImport } from './routes/whitepaper'
import { Route as UscRouteImport } from './routes/usc'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as StatutesRouteImport } from './routes/statutes'
import { Route as StatesRouteImport } from './routes/states'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapPagesDotxmlRouteImport } from './routes/sitemap-pages[.]xml'
import { Route as SitemapOutcomesDotxmlRouteImport } from './routes/sitemap-outcomes[.]xml'
import { Route as SitemapDocsDotxmlRouteImport } from './routes/sitemap-docs[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ScotusRouteImport } from './routes/scotus'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PresidentialRouteImport } from './routes/presidential'
import { Route as ModelRouteImport } from './routes/model'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LawsRouteImport } from './routes/laws'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ForumRouteImport } from './routes/forum'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ConstRouteImport } from './routes/const'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ChambersRouteImport } from './routes/chambers'
import { Route as CfrRouteImport } from './routes/cfr'
import { Route as BillsRouteImport } from './routes/bills'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgencyRouteImport } from './routes/agency'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OutcomesIndexRouteImport } from './routes/outcomes.index'
import { Route as CodeIndexRouteImport } from './routes/code.index'
import { Route as CasesIndexRouteImport } from './routes/cases.index'
import { Route as TopicSlugRouteImport } from './routes/topic.$slug'
import { Route as CompareDiffRouteImport } from './routes/compare_.diff'
import { Route as CodeSplatRouteImport } from './routes/code.$'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as CasesIdRouteImport } from './routes/cases.$id'
import { Route as OutcomesStatesIndexRouteImport } from './routes/outcomes.states.index'
import { Route as ForumSlugIdRouteImport } from './routes/forum_.$slug.$id'
import { Route as CodeSourceSourceRouteImport } from './routes/code.source.$source'
import { Route as OutcomesStatesStateIndexRouteImport } from './routes/outcomes.states.$state.index'
import { Route as OutcomesFederalFamilyIndexRouteImport } from './routes/outcomes.federal.$family.index'
import { Route as OutcomesStatesStateCourtRouteImport } from './routes/outcomes.states.$state.$court'
import { Route as OutcomesFederalFamilyCasetypeRouteImport } from './routes/outcomes.federal.$family.$casetype'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicV1SearchRouteImport } from './routes/api/public/v1/search'
import { Route as ApiPublicV1QuoteRouteImport } from './routes/api/public/v1/quote'
import { Route as ApiPublicV1OpenapiDotjsonRouteImport } from './routes/api/public/v1/openapi[.]json'
import { Route as ApiPublicV1IngestNdjsonRouteImport } from './routes/api/public/v1/ingest-ndjson'
import { Route as ApiPublicV1IngestBatchRouteImport } from './routes/api/public/v1/ingest-batch'
import { Route as ApiPublicV1ExportDocumentsRouteImport } from './routes/api/public/v1/export-documents'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as OutcomesFederalCourtCourtIndexRouteImport } from './routes/outcomes.federal.court.$court.index'
import { Route as OutcomesFederalCourtCourtCasetypeRouteImport } from './routes/outcomes.federal.court.$court.$casetype'
import { Route as ApiPublicV1DocSplatRouteImport } from './routes/api/public/v1/doc/$'

const WhitepaperRoute = WhitepaperRouteImport.update({
  id: '/whitepaper',
  path: '/whitepaper',
  getParentRoute: () => rootRouteImport,
} as any)
const UscRoute = UscRouteImport.update({
  id: '/usc',
  path: '/usc',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const StatutesRoute = StatutesRouteImport.update({
  id: '/statutes',
  path: '/statutes',
  getParentRoute: () => rootRouteImport,
} as any)
const StatesRoute = StatesRouteImport.update({
  id: '/states',
  path: '/states',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapPagesDotxmlRoute = SitemapPagesDotxmlRouteImport.update({
  id: '/sitemap-pages.xml',
  path: '/sitemap-pages.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapOutcomesDotxmlRoute = SitemapOutcomesDotxmlRouteImport.update({
  id: '/sitemap-outcomes.xml',
  path: '/sitemap-outcomes.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDocsDotxmlRoute = SitemapDocsDotxmlRouteImport.update({
  id: '/sitemap-docs.xml',
  path: '/sitemap-docs.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ScotusRoute = ScotusRouteImport.update({
  id: '/scotus',
  path: '/scotus',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PresidentialRoute = PresidentialRouteImport.update({
  id: '/presidential',
  path: '/presidential',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelRoute = ModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LawsRoute = LawsRouteImport.update({
  id: '/laws',
  path: '/laws',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumRoute = ForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstRoute = ConstRouteImport.update({
  id: '/const',
  path: '/const',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ChambersRoute = ChambersRouteImport.update({
  id: '/chambers',
  path: '/chambers',
  getParentRoute: () => rootRouteImport,
} as any)
const CfrRoute = CfrRouteImport.update({
  id: '/cfr',
  path: '/cfr',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsRoute = BillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyRoute = AgencyRouteImport.update({
  id: '/agency',
  path: '/agency',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OutcomesIndexRoute = OutcomesIndexRouteImport.update({
  id: '/outcomes/',
  path: '/outcomes/',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeIndexRoute = CodeIndexRouteImport.update({
  id: '/code/',
  path: '/code/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicSlugRoute = TopicSlugRouteImport.update({
  id: '/topic/$slug',
  path: '/topic/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareDiffRoute = CompareDiffRouteImport.update({
  id: '/compare_/diff',
  path: '/compare/diff',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeSplatRoute = CodeSplatRouteImport.update({
  id: '/code/$',
  path: '/code/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIdRoute = CasesIdRouteImport.update({
  id: '/cases/$id',
  path: '/cases/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OutcomesStatesIndexRoute = OutcomesStatesIndexRouteImport.update({
  id: '/outcomes/states/',
  path: '/outcomes/states/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumSlugIdRoute = ForumSlugIdRouteImport.update({
  id: '/forum_/$slug/$id',
  path: '/forum/$slug/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeSourceSourceRoute = CodeSourceSourceRouteImport.update({
  id: '/code/source/$source',
  path: '/code/source/$source',
  getParentRoute: () => rootRouteImport,
} as any)
const OutcomesStatesStateIndexRoute =
  OutcomesStatesStateIndexRouteImport.update({
    id: '/outcomes/states/$state/',
    path: '/outcomes/states/$state/',
    getParentRoute: () => rootRouteImport,
  } as any)
const OutcomesFederalFamilyIndexRoute =
  OutcomesFederalFamilyIndexRouteImport.update({
    id: '/outcomes/federal/$family/',
    path: '/outcomes/federal/$family/',
    getParentRoute: () => rootRouteImport,
  } as any)
const OutcomesStatesStateCourtRoute =
  OutcomesStatesStateCourtRouteImport.update({
    id: '/outcomes/states/$state/$court',
    path: '/outcomes/states/$state/$court',
    getParentRoute: () => rootRouteImport,
  } as any)
const OutcomesFederalFamilyCasetypeRoute =
  OutcomesFederalFamilyCasetypeRouteImport.update({
    id: '/outcomes/federal/$family/$casetype',
    path: '/outcomes/federal/$family/$casetype',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1SearchRoute = ApiPublicV1SearchRouteImport.update({
  id: '/api/public/v1/search',
  path: '/api/public/v1/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1QuoteRoute = ApiPublicV1QuoteRouteImport.update({
  id: '/api/public/v1/quote',
  path: '/api/public/v1/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1OpenapiDotjsonRoute =
  ApiPublicV1OpenapiDotjsonRouteImport.update({
    id: '/api/public/v1/openapi.json',
    path: '/api/public/v1/openapi.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1IngestNdjsonRoute = ApiPublicV1IngestNdjsonRouteImport.update({
  id: '/api/public/v1/ingest-ndjson',
  path: '/api/public/v1/ingest-ndjson',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1IngestBatchRoute = ApiPublicV1IngestBatchRouteImport.update({
  id: '/api/public/v1/ingest-batch',
  path: '/api/public/v1/ingest-batch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ExportDocumentsRoute =
  ApiPublicV1ExportDocumentsRouteImport.update({
    id: '/api/public/v1/export-documents',
    path: '/api/public/v1/export-documents',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const OutcomesFederalCourtCourtIndexRoute =
  OutcomesFederalCourtCourtIndexRouteImport.update({
    id: '/outcomes/federal/court/$court/',
    path: '/outcomes/federal/court/$court/',
    getParentRoute: () => rootRouteImport,
  } as any)
const OutcomesFederalCourtCourtCasetypeRoute =
  OutcomesFederalCourtCourtCasetypeRouteImport.update({
    id: '/outcomes/federal/court/$court/$casetype',
    path: '/outcomes/federal/court/$court/$casetype',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1DocSplatRoute = ApiPublicV1DocSplatRouteImport.update({
  id: '/api/public/v1/doc/$',
  path: '/api/public/v1/doc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/agency': typeof AgencyRoute
  '/auth': typeof AuthRoute
  '/bills': typeof BillsRoute
  '/cfr': typeof CfrRoute
  '/chambers': typeof ChambersRoute
  '/compare': typeof CompareRoute
  '/const': typeof ConstRoute
  '/features': typeof FeaturesRoute
  '/forum': typeof ForumRoute
  '/how-it-works': typeof HowItWorksRoute
  '/laws': typeof LawsRoute
  '/library': typeof LibraryRoute
  '/model': typeof ModelRoute
  '/presidential': typeof PresidentialRoute
  '/register': typeof RegisterRoute
  '/scotus': typeof ScotusRoute
  '/search': typeof SearchRoute
  '/sitemap-docs.xml': typeof SitemapDocsDotxmlRoute
  '/sitemap-outcomes.xml': typeof SitemapOutcomesDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/states': typeof StatesRoute
  '/statutes': typeof StatutesRoute
  '/subscribe': typeof SubscribeRoute
  '/usc': typeof UscRoute
  '/whitepaper': typeof WhitepaperRoute
  '/cases/$id': typeof CasesIdRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/code/$': typeof CodeSplatRoute
  '/compare/diff': typeof CompareDiffRoute
  '/topic/$slug': typeof TopicSlugRoute
  '/cases/': typeof CasesIndexRoute
  '/code/': typeof CodeIndexRoute
  '/outcomes/': typeof OutcomesIndexRoute
  '/code/source/$source': typeof CodeSourceSourceRoute
  '/forum/$slug/$id': typeof ForumSlugIdRoute
  '/outcomes/states/': typeof OutcomesStatesIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/v1/export-documents': typeof ApiPublicV1ExportDocumentsRoute
  '/api/public/v1/ingest-batch': typeof ApiPublicV1IngestBatchRoute
  '/api/public/v1/ingest-ndjson': typeof ApiPublicV1IngestNdjsonRoute
  '/api/public/v1/openapi.json': typeof ApiPublicV1OpenapiDotjsonRoute
  '/api/public/v1/quote': typeof ApiPublicV1QuoteRoute
  '/api/public/v1/search': typeof ApiPublicV1SearchRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/outcomes/federal/$family/$casetype': typeof OutcomesFederalFamilyCasetypeRoute
  '/outcomes/states/$state/$court': typeof OutcomesStatesStateCourtRoute
  '/outcomes/federal/$family/': typeof OutcomesFederalFamilyIndexRoute
  '/outcomes/states/$state/': typeof OutcomesStatesStateIndexRoute
  '/api/public/v1/doc/$': typeof ApiPublicV1DocSplatRoute
  '/outcomes/federal/court/$court/$casetype': typeof OutcomesFederalCourtCourtCasetypeRoute
  '/outcomes/federal/court/$court/': typeof OutcomesFederalCourtCourtIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/agency': typeof AgencyRoute
  '/auth': typeof AuthRoute
  '/bills': typeof BillsRoute
  '/cfr': typeof CfrRoute
  '/chambers': typeof ChambersRoute
  '/compare': typeof CompareRoute
  '/const': typeof ConstRoute
  '/features': typeof FeaturesRoute
  '/forum': typeof ForumRoute
  '/how-it-works': typeof HowItWorksRoute
  '/laws': typeof LawsRoute
  '/library': typeof LibraryRoute
  '/model': typeof ModelRoute
  '/presidential': typeof PresidentialRoute
  '/register': typeof RegisterRoute
  '/scotus': typeof ScotusRoute
  '/search': typeof SearchRoute
  '/sitemap-docs.xml': typeof SitemapDocsDotxmlRoute
  '/sitemap-outcomes.xml': typeof SitemapOutcomesDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/states': typeof StatesRoute
  '/statutes': typeof StatutesRoute
  '/subscribe': typeof SubscribeRoute
  '/usc': typeof UscRoute
  '/whitepaper': typeof WhitepaperRoute
  '/cases/$id': typeof CasesIdRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/code/$': typeof CodeSplatRoute
  '/compare/diff': typeof CompareDiffRoute
  '/topic/$slug': typeof TopicSlugRoute
  '/cases': typeof CasesIndexRoute
  '/code': typeof CodeIndexRoute
  '/outcomes': typeof OutcomesIndexRoute
  '/code/source/$source': typeof CodeSourceSourceRoute
  '/forum/$slug/$id': typeof ForumSlugIdRoute
  '/outcomes/states': typeof OutcomesStatesIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/v1/export-documents': typeof ApiPublicV1ExportDocumentsRoute
  '/api/public/v1/ingest-batch': typeof ApiPublicV1IngestBatchRoute
  '/api/public/v1/ingest-ndjson': typeof ApiPublicV1IngestNdjsonRoute
  '/api/public/v1/openapi.json': typeof ApiPublicV1OpenapiDotjsonRoute
  '/api/public/v1/quote': typeof ApiPublicV1QuoteRoute
  '/api/public/v1/search': typeof ApiPublicV1SearchRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/outcomes/federal/$family/$casetype': typeof OutcomesFederalFamilyCasetypeRoute
  '/outcomes/states/$state/$court': typeof OutcomesStatesStateCourtRoute
  '/outcomes/federal/$family': typeof OutcomesFederalFamilyIndexRoute
  '/outcomes/states/$state': typeof OutcomesStatesStateIndexRoute
  '/api/public/v1/doc/$': typeof ApiPublicV1DocSplatRoute
  '/outcomes/federal/court/$court/$casetype': typeof OutcomesFederalCourtCourtCasetypeRoute
  '/outcomes/federal/court/$court': typeof OutcomesFederalCourtCourtIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/agency': typeof AgencyRoute
  '/auth': typeof AuthRoute
  '/bills': typeof BillsRoute
  '/cfr': typeof CfrRoute
  '/chambers': typeof ChambersRoute
  '/compare': typeof CompareRoute
  '/const': typeof ConstRoute
  '/features': typeof FeaturesRoute
  '/forum': typeof ForumRoute
  '/how-it-works': typeof HowItWorksRoute
  '/laws': typeof LawsRoute
  '/library': typeof LibraryRoute
  '/model': typeof ModelRoute
  '/presidential': typeof PresidentialRoute
  '/register': typeof RegisterRoute
  '/scotus': typeof ScotusRoute
  '/search': typeof SearchRoute
  '/sitemap-docs.xml': typeof SitemapDocsDotxmlRoute
  '/sitemap-outcomes.xml': typeof SitemapOutcomesDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/states': typeof StatesRoute
  '/statutes': typeof StatutesRoute
  '/subscribe': typeof SubscribeRoute
  '/usc': typeof UscRoute
  '/whitepaper': typeof WhitepaperRoute
  '/cases/$id': typeof CasesIdRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/code/$': typeof CodeSplatRoute
  '/compare_/diff': typeof CompareDiffRoute
  '/topic/$slug': typeof TopicSlugRoute
  '/cases/': typeof CasesIndexRoute
  '/code/': typeof CodeIndexRoute
  '/outcomes/': typeof OutcomesIndexRoute
  '/code/source/$source': typeof CodeSourceSourceRoute
  '/forum_/$slug/$id': typeof ForumSlugIdRoute
  '/outcomes/states/': typeof OutcomesStatesIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/v1/export-documents': typeof ApiPublicV1ExportDocumentsRoute
  '/api/public/v1/ingest-batch': typeof ApiPublicV1IngestBatchRoute
  '/api/public/v1/ingest-ndjson': typeof ApiPublicV1IngestNdjsonRoute
  '/api/public/v1/openapi.json': typeof ApiPublicV1OpenapiDotjsonRoute
  '/api/public/v1/quote': typeof ApiPublicV1QuoteRoute
  '/api/public/v1/search': typeof ApiPublicV1SearchRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/outcomes/federal/$family/$casetype': typeof OutcomesFederalFamilyCasetypeRoute
  '/outcomes/states/$state/$court': typeof OutcomesStatesStateCourtRoute
  '/outcomes/federal/$family/': typeof OutcomesFederalFamilyIndexRoute
  '/outcomes/states/$state/': typeof OutcomesStatesStateIndexRoute
  '/api/public/v1/doc/$': typeof ApiPublicV1DocSplatRoute
  '/outcomes/federal/court/$court/$casetype': typeof OutcomesFederalCourtCourtCasetypeRoute
  '/outcomes/federal/court/$court/': typeof OutcomesFederalCourtCourtIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/agency'
    | '/auth'
    | '/bills'
    | '/cfr'
    | '/chambers'
    | '/compare'
    | '/const'
    | '/features'
    | '/forum'
    | '/how-it-works'
    | '/laws'
    | '/library'
    | '/model'
    | '/presidential'
    | '/register'
    | '/scotus'
    | '/search'
    | '/sitemap-docs.xml'
    | '/sitemap-outcomes.xml'
    | '/sitemap-pages.xml'
    | '/sitemap.xml'
    | '/states'
    | '/statutes'
    | '/subscribe'
    | '/usc'
    | '/whitepaper'
    | '/cases/$id'
    | '/checkout/return'
    | '/code/$'
    | '/compare/diff'
    | '/topic/$slug'
    | '/cases/'
    | '/code/'
    | '/outcomes/'
    | '/code/source/$source'
    | '/forum/$slug/$id'
    | '/outcomes/states/'
    | '/api/public/payments/webhook'
    | '/api/public/v1/export-documents'
    | '/api/public/v1/ingest-batch'
    | '/api/public/v1/ingest-ndjson'
    | '/api/public/v1/openapi.json'
    | '/api/public/v1/quote'
    | '/api/public/v1/search'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/outcomes/federal/$family/$casetype'
    | '/outcomes/states/$state/$court'
    | '/outcomes/federal/$family/'
    | '/outcomes/states/$state/'
    | '/api/public/v1/doc/$'
    | '/outcomes/federal/court/$court/$casetype'
    | '/outcomes/federal/court/$court/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/agency'
    | '/auth'
    | '/bills'
    | '/cfr'
    | '/chambers'
    | '/compare'
    | '/const'
    | '/features'
    | '/forum'
    | '/how-it-works'
    | '/laws'
    | '/library'
    | '/model'
    | '/presidential'
    | '/register'
    | '/scotus'
    | '/search'
    | '/sitemap-docs.xml'
    | '/sitemap-outcomes.xml'
    | '/sitemap-pages.xml'
    | '/sitemap.xml'
    | '/states'
    | '/statutes'
    | '/subscribe'
    | '/usc'
    | '/whitepaper'
    | '/cases/$id'
    | '/checkout/return'
    | '/code/$'
    | '/compare/diff'
    | '/topic/$slug'
    | '/cases'
    | '/code'
    | '/outcomes'
    | '/code/source/$source'
    | '/forum/$slug/$id'
    | '/outcomes/states'
    | '/api/public/payments/webhook'
    | '/api/public/v1/export-documents'
    | '/api/public/v1/ingest-batch'
    | '/api/public/v1/ingest-ndjson'
    | '/api/public/v1/openapi.json'
    | '/api/public/v1/quote'
    | '/api/public/v1/search'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/outcomes/federal/$family/$casetype'
    | '/outcomes/states/$state/$court'
    | '/outcomes/federal/$family'
    | '/outcomes/states/$state'
    | '/api/public/v1/doc/$'
    | '/outcomes/federal/court/$court/$casetype'
    | '/outcomes/federal/court/$court'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/agency'
    | '/auth'
    | '/bills'
    | '/cfr'
    | '/chambers'
    | '/compare'
    | '/const'
    | '/features'
    | '/forum'
    | '/how-it-works'
    | '/laws'
    | '/library'
    | '/model'
    | '/presidential'
    | '/register'
    | '/scotus'
    | '/search'
    | '/sitemap-docs.xml'
    | '/sitemap-outcomes.xml'
    | '/sitemap-pages.xml'
    | '/sitemap.xml'
    | '/states'
    | '/statutes'
    | '/subscribe'
    | '/usc'
    | '/whitepaper'
    | '/cases/$id'
    | '/checkout/return'
    | '/code/$'
    | '/compare_/diff'
    | '/topic/$slug'
    | '/cases/'
    | '/code/'
    | '/outcomes/'
    | '/code/source/$source'
    | '/forum_/$slug/$id'
    | '/outcomes/states/'
    | '/api/public/payments/webhook'
    | '/api/public/v1/export-documents'
    | '/api/public/v1/ingest-batch'
    | '/api/public/v1/ingest-ndjson'
    | '/api/public/v1/openapi.json'
    | '/api/public/v1/quote'
    | '/api/public/v1/search'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/outcomes/federal/$family/$casetype'
    | '/outcomes/states/$state/$court'
    | '/outcomes/federal/$family/'
    | '/outcomes/states/$state/'
    | '/api/public/v1/doc/$'
    | '/outcomes/federal/court/$court/$casetype'
    | '/outcomes/federal/court/$court/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AgencyRoute: typeof AgencyRoute
  AuthRoute: typeof AuthRoute
  BillsRoute: typeof BillsRoute
  CfrRoute: typeof CfrRoute
  ChambersRoute: typeof ChambersRoute
  CompareRoute: typeof CompareRoute
  ConstRoute: typeof ConstRoute
  FeaturesRoute: typeof FeaturesRoute
  ForumRoute: typeof ForumRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LawsRoute: typeof LawsRoute
  LibraryRoute: typeof LibraryRoute
  ModelRoute: typeof ModelRoute
  PresidentialRoute: typeof PresidentialRoute
  RegisterRoute: typeof RegisterRoute
  ScotusRoute: typeof ScotusRoute
  SearchRoute: typeof SearchRoute
  SitemapDocsDotxmlRoute: typeof SitemapDocsDotxmlRoute
  SitemapOutcomesDotxmlRoute: typeof SitemapOutcomesDotxmlRoute
  SitemapPagesDotxmlRoute: typeof SitemapPagesDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatesRoute: typeof StatesRoute
  StatutesRoute: typeof StatutesRoute
  SubscribeRoute: typeof SubscribeRoute
  UscRoute: typeof UscRoute
  WhitepaperRoute: typeof WhitepaperRoute
  CasesIdRoute: typeof CasesIdRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  CodeSplatRoute: typeof CodeSplatRoute
  CompareDiffRoute: typeof CompareDiffRoute
  TopicSlugRoute: typeof TopicSlugRoute
  CasesIndexRoute: typeof CasesIndexRoute
  CodeIndexRoute: typeof CodeIndexRoute
  OutcomesIndexRoute: typeof OutcomesIndexRoute
  CodeSourceSourceRoute: typeof CodeSourceSourceRoute
  ForumSlugIdRoute: typeof ForumSlugIdRoute
  OutcomesStatesIndexRoute: typeof OutcomesStatesIndexRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicV1ExportDocumentsRoute: typeof ApiPublicV1ExportDocumentsRoute
  ApiPublicV1IngestBatchRoute: typeof ApiPublicV1IngestBatchRoute
  ApiPublicV1IngestNdjsonRoute: typeof ApiPublicV1IngestNdjsonRoute
  ApiPublicV1OpenapiDotjsonRoute: typeof ApiPublicV1OpenapiDotjsonRoute
  ApiPublicV1QuoteRoute: typeof ApiPublicV1QuoteRoute
  ApiPublicV1SearchRoute: typeof ApiPublicV1SearchRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  OutcomesFederalFamilyCasetypeRoute: typeof OutcomesFederalFamilyCasetypeRoute
  OutcomesStatesStateCourtRoute: typeof OutcomesStatesStateCourtRoute
  OutcomesFederalFamilyIndexRoute: typeof OutcomesFederalFamilyIndexRoute
  OutcomesStatesStateIndexRoute: typeof OutcomesStatesStateIndexRoute
  ApiPublicV1DocSplatRoute: typeof ApiPublicV1DocSplatRoute
  OutcomesFederalCourtCourtCasetypeRoute: typeof OutcomesFederalCourtCourtCasetypeRoute
  OutcomesFederalCourtCourtIndexRoute: typeof OutcomesFederalCourtCourtIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whitepaper': {
      id: '/whitepaper'
      path: '/whitepaper'
      fullPath: '/whitepaper'
      preLoaderRoute: typeof WhitepaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usc': {
      id: '/usc'
      path: '/usc'
      fullPath: '/usc'
      preLoaderRoute: typeof UscRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statutes': {
      id: '/statutes'
      path: '/statutes'
      fullPath: '/statutes'
      preLoaderRoute: typeof StatutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/states': {
      id: '/states'
      path: '/states'
      fullPath: '/states'
      preLoaderRoute: typeof StatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-pages.xml': {
      id: '/sitemap-pages.xml'
      path: '/sitemap-pages.xml'
      fullPath: '/sitemap-pages.xml'
      preLoaderRoute: typeof SitemapPagesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-outcomes.xml': {
      id: '/sitemap-outcomes.xml'
      path: '/sitemap-outcomes.xml'
      fullPath: '/sitemap-outcomes.xml'
      preLoaderRoute: typeof SitemapOutcomesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-docs.xml': {
      id: '/sitemap-docs.xml'
      path: '/sitemap-docs.xml'
      fullPath: '/sitemap-docs.xml'
      preLoaderRoute: typeof SitemapDocsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scotus': {
      id: '/scotus'
      path: '/scotus'
      fullPath: '/scotus'
      preLoaderRoute: typeof ScotusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presidential': {
      id: '/presidential'
      path: '/presidential'
      fullPath: '/presidential'
      preLoaderRoute: typeof PresidentialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model': {
      id: '/model'
      path: '/model'
      fullPath: '/model'
      preLoaderRoute: typeof ModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laws': {
      id: '/laws'
      path: '/laws'
      fullPath: '/laws'
      preLoaderRoute: typeof LawsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum': {
      id: '/forum'
      path: '/forum'
      fullPath: '/forum'
      preLoaderRoute: typeof ForumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/const': {
      id: '/const'
      path: '/const'
      fullPath: '/const'
      preLoaderRoute: typeof ConstRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chambers': {
      id: '/chambers'
      path: '/chambers'
      fullPath: '/chambers'
      preLoaderRoute: typeof ChambersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cfr': {
      id: '/cfr'
      path: '/cfr'
      fullPath: '/cfr'
      preLoaderRoute: typeof CfrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills': {
      id: '/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof BillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency': {
      id: '/agency'
      path: '/agency'
      fullPath: '/agency'
      preLoaderRoute: typeof AgencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outcomes/': {
      id: '/outcomes/'
      path: '/outcomes'
      fullPath: '/outcomes/'
      preLoaderRoute: typeof OutcomesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code/': {
      id: '/code/'
      path: '/code'
      fullPath: '/code/'
      preLoaderRoute: typeof CodeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/': {
      id: '/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topic/$slug': {
      id: '/topic/$slug'
      path: '/topic/$slug'
      fullPath: '/topic/$slug'
      preLoaderRoute: typeof TopicSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare_/diff': {
      id: '/compare_/diff'
      path: '/compare/diff'
      fullPath: '/compare/diff'
      preLoaderRoute: typeof CompareDiffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code/$': {
      id: '/code/$'
      path: '/code/$'
      fullPath: '/code/$'
      preLoaderRoute: typeof CodeSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$id': {
      id: '/cases/$id'
      path: '/cases/$id'
      fullPath: '/cases/$id'
      preLoaderRoute: typeof CasesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outcomes/states/': {
      id: '/outcomes/states/'
      path: '/outcomes/states'
      fullPath: '/outcomes/states/'
      preLoaderRoute: typeof OutcomesStatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum_/$slug/$id': {
      id: '/forum_/$slug/$id'
      path: '/forum/$slug/$id'
      fullPath: '/forum/$slug/$id'
      preLoaderRoute: typeof ForumSlugIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code/source/$source': {
      id: '/code/source/$source'
      path: '/code/source/$source'
      fullPath: '/code/source/$source'
      preLoaderRoute: typeof CodeSourceSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outcomes/states/$state/': {
      id: '/outcomes/states/$state/'
      path: '/outcomes/states/$state'
      fullPath: '/outcomes/states/$state/'
      preLoaderRoute: typeof OutcomesStatesStateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outcomes/federal/$family/': {
      id: '/outcomes/federal/$family/'
      path: '/outcomes/federal/$family'
      fullPath: '/outcomes/federal/$family/'
      preLoaderRoute: typeof OutcomesFederalFamilyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outcomes/states/$state/$court': {
      id: '/outcomes/states/$state/$court'
      path: '/outcomes/states/$state/$court'
      fullPath: '/outcomes/states/$state/$court'
      preLoaderRoute: typeof OutcomesStatesStateCourtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outcomes/federal/$family/$casetype': {
      id: '/outcomes/federal/$family/$casetype'
      path: '/outcomes/federal/$family/$casetype'
      fullPath: '/outcomes/federal/$family/$casetype'
      preLoaderRoute: typeof OutcomesFederalFamilyCasetypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/search': {
      id: '/api/public/v1/search'
      path: '/api/public/v1/search'
      fullPath: '/api/public/v1/search'
      preLoaderRoute: typeof ApiPublicV1SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/quote': {
      id: '/api/public/v1/quote'
      path: '/api/public/v1/quote'
      fullPath: '/api/public/v1/quote'
      preLoaderRoute: typeof ApiPublicV1QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/openapi.json': {
      id: '/api/public/v1/openapi.json'
      path: '/api/public/v1/openapi.json'
      fullPath: '/api/public/v1/openapi.json'
      preLoaderRoute: typeof ApiPublicV1OpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/ingest-ndjson': {
      id: '/api/public/v1/ingest-ndjson'
      path: '/api/public/v1/ingest-ndjson'
      fullPath: '/api/public/v1/ingest-ndjson'
      preLoaderRoute: typeof ApiPublicV1IngestNdjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/ingest-batch': {
      id: '/api/public/v1/ingest-batch'
      path: '/api/public/v1/ingest-batch'
      fullPath: '/api/public/v1/ingest-batch'
      preLoaderRoute: typeof ApiPublicV1IngestBatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/export-documents': {
      id: '/api/public/v1/export-documents'
      path: '/api/public/v1/export-documents'
      fullPath: '/api/public/v1/export-documents'
      preLoaderRoute: typeof ApiPublicV1ExportDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outcomes/federal/court/$court/': {
      id: '/outcomes/federal/court/$court/'
      path: '/outcomes/federal/court/$court'
      fullPath: '/outcomes/federal/court/$court/'
      preLoaderRoute: typeof OutcomesFederalCourtCourtIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outcomes/federal/court/$court/$casetype': {
      id: '/outcomes/federal/court/$court/$casetype'
      path: '/outcomes/federal/court/$court/$casetype'
      fullPath: '/outcomes/federal/court/$court/$casetype'
      preLoaderRoute: typeof OutcomesFederalCourtCourtCasetypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/doc/$': {
      id: '/api/public/v1/doc/$'
      path: '/api/public/v1/doc/$'
      fullPath: '/api/public/v1/doc/$'
      preLoaderRoute: typeof ApiPublicV1DocSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AgencyRoute: AgencyRoute,
  AuthRoute: AuthRoute,
  BillsRoute: BillsRoute,
  CfrRoute: CfrRoute,
  ChambersRoute: ChambersRoute,
  CompareRoute: CompareRoute,
  ConstRoute: ConstRoute,
  FeaturesRoute: FeaturesRoute,
  ForumRoute: ForumRoute,
  HowItWorksRoute: HowItWorksRoute,
  LawsRoute: LawsRoute,
  LibraryRoute: LibraryRoute,
  ModelRoute: ModelRoute,
  PresidentialRoute: PresidentialRoute,
  RegisterRoute: RegisterRoute,
  ScotusRoute: ScotusRoute,
  SearchRoute: SearchRoute,
  SitemapDocsDotxmlRoute: SitemapDocsDotxmlRoute,
  SitemapOutcomesDotxmlRoute: SitemapOutcomesDotxmlRoute,
  SitemapPagesDotxmlRoute: SitemapPagesDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatesRoute: StatesRoute,
  StatutesRoute: StatutesRoute,
  SubscribeRoute: SubscribeRoute,
  UscRoute: UscRoute,
  WhitepaperRoute: WhitepaperRoute,
  CasesIdRoute: CasesIdRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  CodeSplatRoute: CodeSplatRoute,
  CompareDiffRoute: CompareDiffRoute,
  TopicSlugRoute: TopicSlugRoute,
  CasesIndexRoute: CasesIndexRoute,
  CodeIndexRoute: CodeIndexRoute,
  OutcomesIndexRoute: OutcomesIndexRoute,
  CodeSourceSourceRoute: CodeSourceSourceRoute,
  ForumSlugIdRoute: ForumSlugIdRoute,
  OutcomesStatesIndexRoute: OutcomesStatesIndexRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicV1ExportDocumentsRoute: ApiPublicV1ExportDocumentsRoute,
  ApiPublicV1IngestBatchRoute: ApiPublicV1IngestBatchRoute,
  ApiPublicV1IngestNdjsonRoute: ApiPublicV1IngestNdjsonRoute,
  ApiPublicV1OpenapiDotjsonRoute: ApiPublicV1OpenapiDotjsonRoute,
  ApiPublicV1QuoteRoute: ApiPublicV1QuoteRoute,
  ApiPublicV1SearchRoute: ApiPublicV1SearchRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  OutcomesFederalFamilyCasetypeRoute: OutcomesFederalFamilyCasetypeRoute,
  OutcomesStatesStateCourtRoute: OutcomesStatesStateCourtRoute,
  OutcomesFederalFamilyIndexRoute: OutcomesFederalFamilyIndexRoute,
  OutcomesStatesStateIndexRoute: OutcomesStatesStateIndexRoute,
  ApiPublicV1DocSplatRoute: ApiPublicV1DocSplatRoute,
  OutcomesFederalCourtCourtCasetypeRoute:
    OutcomesFederalCourtCourtCasetypeRoute,
  OutcomesFederalCourtCourtIndexRoute: OutcomesFederalCourtCourtIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
