/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhitepaperRouteImport } from './routes/whitepaper'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as StacksRouteImport } from './routes/stacks'
import { Route as SearchRouteImport } from './routes/search'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ForumRouteImport } from './routes/forum'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ChambersRouteImport } from './routes/chambers'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CodeIndexRouteImport } from './routes/code.index'
import { Route as CasesIndexRouteImport } from './routes/cases.index'
import { Route as TopicSlugRouteImport } from './routes/topic.$slug'
import { Route as StacksViewRouteImport } from './routes/stacks.view'
import { Route as CodeSplatRouteImport } from './routes/code.$'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as CasesCaseIdRouteImport } from './routes/cases.$caseId'
import { Route as CodeSourceSourceRouteImport } from './routes/code.source.$source'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const WhitepaperRoute = WhitepaperRouteImport.update({
  id: '/whitepaper',
  path: '/whitepaper',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const StacksRoute = StacksRouteImport.update({
  id: '/stacks',
  path: '/stacks',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumRoute = ForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ChambersRoute = ChambersRouteImport.update({
  id: '/chambers',
  path: '/chambers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeIndexRoute = CodeIndexRouteImport.update({
  id: '/code/',
  path: '/code/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicSlugRoute = TopicSlugRouteImport.update({
  id: '/topic/$slug',
  path: '/topic/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StacksViewRoute = StacksViewRouteImport.update({
  id: '/view',
  path: '/view',
  getParentRoute: () => StacksRoute,
} as any)
const CodeSplatRoute = CodeSplatRouteImport.update({
  id: '/code/$',
  path: '/code/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCaseIdRoute = CasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeSourceSourceRoute = CodeSourceSourceRouteImport.update({
  id: '/code/source/$source',
  path: '/code/source/$source',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/chambers': typeof ChambersRoute
  '/compare': typeof CompareRoute
  '/forum': typeof ForumRoute
  '/library': typeof LibraryRoute
  '/search': typeof SearchRoute
  '/stacks': typeof StacksRouteWithChildren
  '/subscribe': typeof SubscribeRoute
  '/whitepaper': typeof WhitepaperRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/code/$': typeof CodeSplatRoute
  '/stacks/view': typeof StacksViewRoute
  '/topic/$slug': typeof TopicSlugRoute
  '/cases/': typeof CasesIndexRoute
  '/code/': typeof CodeIndexRoute
  '/code/source/$source': typeof CodeSourceSourceRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/chambers': typeof ChambersRoute
  '/compare': typeof CompareRoute
  '/forum': typeof ForumRoute
  '/library': typeof LibraryRoute
  '/search': typeof SearchRoute
  '/stacks': typeof StacksRouteWithChildren
  '/subscribe': typeof SubscribeRoute
  '/whitepaper': typeof WhitepaperRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/code/$': typeof CodeSplatRoute
  '/stacks/view': typeof StacksViewRoute
  '/topic/$slug': typeof TopicSlugRoute
  '/cases': typeof CasesIndexRoute
  '/code': typeof CodeIndexRoute
  '/code/source/$source': typeof CodeSourceSourceRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/chambers': typeof ChambersRoute
  '/compare': typeof CompareRoute
  '/forum': typeof ForumRoute
  '/library': typeof LibraryRoute
  '/search': typeof SearchRoute
  '/stacks': typeof StacksRouteWithChildren
  '/subscribe': typeof SubscribeRoute
  '/whitepaper': typeof WhitepaperRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/code/$': typeof CodeSplatRoute
  '/stacks/view': typeof StacksViewRoute
  '/topic/$slug': typeof TopicSlugRoute
  '/cases/': typeof CasesIndexRoute
  '/code/': typeof CodeIndexRoute
  '/code/source/$source': typeof CodeSourceSourceRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/chambers'
    | '/compare'
    | '/forum'
    | '/library'
    | '/search'
    | '/stacks'
    | '/subscribe'
    | '/whitepaper'
    | '/cases/$caseId'
    | '/checkout/return'
    | '/code/$'
    | '/stacks/view'
    | '/topic/$slug'
    | '/cases/'
    | '/code/'
    | '/code/source/$source'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/chambers'
    | '/compare'
    | '/forum'
    | '/library'
    | '/search'
    | '/stacks'
    | '/subscribe'
    | '/whitepaper'
    | '/cases/$caseId'
    | '/checkout/return'
    | '/code/$'
    | '/stacks/view'
    | '/topic/$slug'
    | '/cases'
    | '/code'
    | '/code/source/$source'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/chambers'
    | '/compare'
    | '/forum'
    | '/library'
    | '/search'
    | '/stacks'
    | '/subscribe'
    | '/whitepaper'
    | '/cases/$caseId'
    | '/checkout/return'
    | '/code/$'
    | '/stacks/view'
    | '/topic/$slug'
    | '/cases/'
    | '/code/'
    | '/code/source/$source'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  ChambersRoute: typeof ChambersRoute
  CompareRoute: typeof CompareRoute
  ForumRoute: typeof ForumRoute
  LibraryRoute: typeof LibraryRoute
  SearchRoute: typeof SearchRoute
  StacksRoute: typeof StacksRouteWithChildren
  SubscribeRoute: typeof SubscribeRoute
  WhitepaperRoute: typeof WhitepaperRoute
  CasesCaseIdRoute: typeof CasesCaseIdRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  CodeSplatRoute: typeof CodeSplatRoute
  TopicSlugRoute: typeof TopicSlugRoute
  CasesIndexRoute: typeof CasesIndexRoute
  CodeIndexRoute: typeof CodeIndexRoute
  CodeSourceSourceRoute: typeof CodeSourceSourceRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whitepaper': {
      id: '/whitepaper'
      path: '/whitepaper'
      fullPath: '/whitepaper'
      preLoaderRoute: typeof WhitepaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stacks': {
      id: '/stacks'
      path: '/stacks'
      fullPath: '/stacks'
      preLoaderRoute: typeof StacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum': {
      id: '/forum'
      path: '/forum'
      fullPath: '/forum'
      preLoaderRoute: typeof ForumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chambers': {
      id: '/chambers'
      path: '/chambers'
      fullPath: '/chambers'
      preLoaderRoute: typeof ChambersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code/': {
      id: '/code/'
      path: '/code'
      fullPath: '/code/'
      preLoaderRoute: typeof CodeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/': {
      id: '/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topic/$slug': {
      id: '/topic/$slug'
      path: '/topic/$slug'
      fullPath: '/topic/$slug'
      preLoaderRoute: typeof TopicSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stacks/view': {
      id: '/stacks/view'
      path: '/view'
      fullPath: '/stacks/view'
      preLoaderRoute: typeof StacksViewRouteImport
      parentRoute: typeof StacksRoute
    }
    '/code/$': {
      id: '/code/$'
      path: '/code/$'
      fullPath: '/code/$'
      preLoaderRoute: typeof CodeSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$caseId': {
      id: '/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof CasesCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code/source/$source': {
      id: '/code/source/$source'
      path: '/code/source/$source'
      fullPath: '/code/source/$source'
      preLoaderRoute: typeof CodeSourceSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StacksRouteChildren {
  StacksViewRoute: typeof StacksViewRoute
}

const StacksRouteChildren: StacksRouteChildren = {
  StacksViewRoute: StacksViewRoute,
}

const StacksRouteWithChildren =
  StacksRoute._addFileChildren(StacksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  ChambersRoute: ChambersRoute,
  CompareRoute: CompareRoute,
  ForumRoute: ForumRoute,
  LibraryRoute: LibraryRoute,
  SearchRoute: SearchRoute,
  StacksRoute: StacksRouteWithChildren,
  SubscribeRoute: SubscribeRoute,
  WhitepaperRoute: WhitepaperRoute,
  CasesCaseIdRoute: CasesCaseIdRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  CodeSplatRoute: CodeSplatRoute,
  TopicSlugRoute: TopicSlugRoute,
  CasesIndexRoute: CasesIndexRoute,
  CodeIndexRoute: CodeIndexRoute,
  CodeSourceSourceRoute: CodeSourceSourceRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
