/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CodeIndexRouteImport } from './routes/code.index'
import { Route as TopicSlugRouteImport } from './routes/topic.$slug'
import { Route as CodeSplatRouteImport } from './routes/code.$'
import { Route as CodeSourceSourceRouteImport } from './routes/code.source.$source'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeIndexRoute = CodeIndexRouteImport.update({
  id: '/code/',
  path: '/code/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicSlugRoute = TopicSlugRouteImport.update({
  id: '/topic/$slug',
  path: '/topic/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeSplatRoute = CodeSplatRouteImport.update({
  id: '/code/$',
  path: '/code/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeSourceSourceRoute = CodeSourceSourceRouteImport.update({
  id: '/code/source/$source',
  path: '/code/source/$source',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/library': typeof LibraryRoute
  '/search': typeof SearchRoute
  '/code/$': typeof CodeSplatRoute
  '/topic/$slug': typeof TopicSlugRoute
  '/code/': typeof CodeIndexRoute
  '/code/source/$source': typeof CodeSourceSourceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/library': typeof LibraryRoute
  '/search': typeof SearchRoute
  '/code/$': typeof CodeSplatRoute
  '/topic/$slug': typeof TopicSlugRoute
  '/code': typeof CodeIndexRoute
  '/code/source/$source': typeof CodeSourceSourceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/library': typeof LibraryRoute
  '/search': typeof SearchRoute
  '/code/$': typeof CodeSplatRoute
  '/topic/$slug': typeof TopicSlugRoute
  '/code/': typeof CodeIndexRoute
  '/code/source/$source': typeof CodeSourceSourceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/library'
    | '/search'
    | '/code/$'
    | '/topic/$slug'
    | '/code/'
    | '/code/source/$source'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/library'
    | '/search'
    | '/code/$'
    | '/topic/$slug'
    | '/code'
    | '/code/source/$source'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/library'
    | '/search'
    | '/code/$'
    | '/topic/$slug'
    | '/code/'
    | '/code/source/$source'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LibraryRoute: typeof LibraryRoute
  SearchRoute: typeof SearchRoute
  CodeSplatRoute: typeof CodeSplatRoute
  TopicSlugRoute: typeof TopicSlugRoute
  CodeIndexRoute: typeof CodeIndexRoute
  CodeSourceSourceRoute: typeof CodeSourceSourceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code/': {
      id: '/code/'
      path: '/code'
      fullPath: '/code/'
      preLoaderRoute: typeof CodeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topic/$slug': {
      id: '/topic/$slug'
      path: '/topic/$slug'
      fullPath: '/topic/$slug'
      preLoaderRoute: typeof TopicSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code/$': {
      id: '/code/$'
      path: '/code/$'
      fullPath: '/code/$'
      preLoaderRoute: typeof CodeSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code/source/$source': {
      id: '/code/source/$source'
      path: '/code/source/$source'
      fullPath: '/code/source/$source'
      preLoaderRoute: typeof CodeSourceSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LibraryRoute: LibraryRoute,
  SearchRoute: SearchRoute,
  CodeSplatRoute: CodeSplatRoute,
  TopicSlugRoute: TopicSlugRoute,
  CodeIndexRoute: CodeIndexRoute,
  CodeSourceSourceRoute: CodeSourceSourceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
